name: clink-frontend
static_sites:
  - name: frontend
    github:
      repo: your-username/your-repo-name
      branch: main
      deploy_on_push: true
    build_command: npm ci && npm run build
    output_dir: dist
    # SPA routing - all routes go to index.html
    catchall_document: index.html
    error_document: index.html
    envs:
      - key: VITE_API_BASE_URL
        value: https://api.tailoredpsychology.com.au/api
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: VITE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME
      - key: VITE_APP_NAME
        value: Clink Psychology Clinic
        scope: RUN_AND_BUILD_TIME
      - key: VITE_DEBUG
        value: "false"
        scope: RUN_AND_BUILD_TIME

